homeassistant:
  name: Hem
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Stockholm
  currency: SEK
  packages: !include_dir_named include
  allowlist_external_dirs: [/config/]

default_config:

lovelace:
  mode: yaml
  resources:
    [ { url: /hacsfiles/bar-card/bar-card.js,                               type: module },
      { url: /hacsfiles/button-card/button-card.js,                         type: module },
      { url: /hacsfiles/kiosk-mode/kiosk-mode.js,                           type: module },
      { url: /hacsfiles/light-entity-card/light-entity-card.js,             type: module },
      { url: /hacsfiles/light-popup-card/light-popup-card.js,               type: module },
      { url: /hacsfiles/lovelace-card-mod/card-mod.js,                      type: module },
      { url: /hacsfiles/lovelace-hui-element/hui-element.js,                type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                type: module },
      { url: /hacsfiles/lovelace-more-info-card/more-info-card.js,          type: module },
      { url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,    type: module },
      { url: /hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js,    type: module },
      { url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,          type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                           type: module },

      { url: '/local/calendar-card.js?v=31091',                             type: module },
      { url: '/local/custom_icons.js?v=25052001',                           type: module },
      { url: /local/font.css,                                               type: css    } ]

logger:
  default: warning
  logs:
    homeassistant.components.websocket_api: fatal
    homeassistant.components.bluetooth_tracker.device_tracker: fatal

recorder:
  db_url: !secret recorder_db_url

person:
  - name: Matte
    id: matte
    device_trackers:
      - device_tracker.mattias_iphone_ios
      - device_tracker.mattias_iphonedetect
      - device_tracker.mattias_iphone_unifi
      - device_tracker.mattias_bluetooth

  - name: Sanja
    id: sanja
    device_trackers:
      - device_tracker.sanja_iphonedetect
      - device_tracker.sanjas_iphone_unifi
      - device_tracker.sanja_bluetooth

device_tracker:
  # - platform: bluetooth_tracker
  #   new_device_defaults:
  #     track_new_devices: false

  - platform: iphonedetect
    consider_home: 60
    scan_interval: 12
    new_device_defaults:
      track_new_devices: false
    hosts:
      mattias_iphonedetect: !secret iphonedetect_matte
      sanja_iphonedetect: !secret iphonedetect_sanja

smartir:
  check_updates: false

climate:
  - platform: smartir
    name: Klimat
    unique_id: EXP26U758CW
    device_code: 1703
    controller_data: remote.broadlink_remote
    temperature_sensor: sensor.broadlink_rm4_pro_temperature
    humidity_sensor: sensor.broadlink_rm4_pro_humidity
    power_sensor: binary_sensor.gosund_ac
    power_sensor_restore_state: true

influxdb:
  api_version: 2
  ssl: false
  host: !secret influxdb_host
  port: !secret influxdb_port
  organization: !secret influxdb_org
  token: !secret influxdb_token
  bucket: weight
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
  include:
    entities:
      - sensor.mattias_weight
      - sensor.sanja_weight

waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: !secret waste_collection_schedule_url

wemo:
  discovery: false
  static: !secret wemo_static

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

browser_mod:
  devices:
    c2080cea-6627150a:
      name: galaxy_tab_a
  disable:
    - all

timer:
  laundry:
    duration: 01:00:00
    icon: mdi:washing-machine

lock:
  - platform: template
    name: Dator
    value_template: "{{ states('input_boolean.computer_lock') }}"
    lock:
      service: input_boolean.turn_on
      entity_id: input_boolean.computer_lock
    unlock:
      service: input_boolean.turn_off
      entity_id: input_boolean.computer_lock

ios:
  push:
    categories:
      - name: Home Assistant
        identifier: ios_hass
        actions:
          - identifier: start_watchtower
            title: Uppdatera
