homeassistant:
  name: Hem
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named include
  whitelist_external_dirs: [/config/]

#default_config:
history:
mobile_app:
sun:
system_health:

lovelace:
  mode: yaml
  dashboards:
    ui-experimental:
      title: Experimental
      filename: ui-experimental.yaml
      mode: yaml
  resources:
    [ {url: /hacsfiles/bar-card/bar-card.js,                                     type: module},
      {url: /hacsfiles/button-card/button-card.js,                               type: module},
      {url: /hacsfiles/calendar-card/calendar-card.js,                           type: module},
      {url: /hacsfiles/custom-header/custom-header.js,                           type: module},
      {url: /hacsfiles/light-entity-card/light-entity-card.js,                   type: js},
      {url: /hacsfiles/light-popup-card/light-popup-card.js,                     type: module},
      {url: /hacsfiles/lovelace-card-mod/card-mod.js,                            type: module},
      {url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js,       type: module},
      {url: /hacsfiles/lovelace-hui-element/hui-element.js,                      type: module},
      {url: /hacsfiles/lovelace-layout-card/layout-card.js,                      type: module},
      {url: /hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js,          type: js},
      {url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,                type: module},
      {url: /hacsfiles/mini-media-player/mini-media-player-bundle.js,            type: module},
      {url: /hacsfiles/popup-backdrop-filter/popup-backdrop-filter.js,           type: module},
      {url: /hacsfiles/stack-in-card/stack-in-card.js,                           type: module},
      {url: /hacsfiles/swipe-card/swipe-card.js,                                 type: module},

      {url: '/hacsfiles/lovelace-slider-entity-row/slider-entity-row.js?v=12',   type: module},
      {url: '/local/custom_icons.js?v=25052001',                                 type: module},
      {url: /local/font.css,                                                     type: css} ]

logger:
  default: warning
  logs:
    homeassistant.components.homekit.type_media_players: fatal
    homeassistant.components.command_line.sensor: fatal
    homeassistant.components.rest.sensor: fatal
    bravia_tv.braviarc: fatal
    homeassistant.components.websocket_api: fatal
    homeassistant.helpers.service: fatal
    # homeassistant.components.bluetooth_tracker.device_tracker: fatal
    # homeassistant.components.shell_command: fatal

recorder:
  purge_keep_days: 2
  include:
    entities:
      ['person.mattias', 'person.sanja','sensor.synology_network_up', 'sensor.aktuellt_spotpris', 
      'sensor.synology_network_down', 'sensor.hall_temperature']

person:
  - name: Mattias
    id: mattias6264b484ba6c360555c9a0547
    user_id: 1b8e4036264b484ba6c360555c9a0547
    device_trackers:
      ['device_tracker.mattias', 'device_tracker.iphone', 'device_tracker.mattias_bluetooth']

  - name: Sanja
    id: sanja4543958678435345345345345
    device_trackers:
      ['device_tracker.sanja', 'device_tracker.sanja_bluetooth']

device_tracker:
  - platform: iphonedetect
    consider_home: 120
    new_device_defaults:
      track_new_devices: false
    hosts:
      Mattias: !secret iphonedetect_mattias
      Sanja: !secret iphonedetect_sanja

  - platform: bluetooth_tracker

hue:
  bridges:
    - host: !secret hue_host
      allow_unreachable: true

remote:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac
    type: rm4_pro

wemo:
  discovery: false
  static: !secret wemo_static

cast:
  media_player:
    - host: !secret google_cast_host

samsungtv:
  - host: !secret samsungtv_host

hacs:
  token: !secret hacs_token

synology_dsm:
  - host: !secret synologydsm_host
    port: !secret synologydsm_port
    ssl: false
    username: !secret synologydsm_username
    password: !secret synologydsm_password

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

vacuum:
  - platform: xiaomi_miio
    host: !secret roborock_host
    token: !secret roborock_token

tts:
  - platform: google_translate
    language: 'sv'
    base_url: !secret tts_base_url

mqtt:
  broker: !secret mqtt_broker
  discovery: true
  discovery_prefix: homeassistant

browser_mod:
  devices:
    918296e3-e2a54976:
      name: imac_chrome
    c2080cea-6627150a:
      name: tablet

timer:
  laundry:
    duration: 01:00:00
    icon: mdi:washing-machine

shell_command:
  # Setup on macos
  # System Preferences > Sharing > Remote Login
  # ssh root@hassio.local
  # ssh-keygen
  # /config/.ssh/id_rsa
  # ssh-copy-id -i /config/.ssh/id_rsa USER@XXX.XXX.X.X

  imac_switchbot_rpi: !secret imac_switchbot_rpi
  imac_turn_off: !secret imac_turn_off
  imac_sleep: !secret imac_sleep
  imac_restart: !secret imac_restart
  imac_notify_motion_hallway: !secret imac_notify_motion_hallway
  imac_notify_laundry: !secret imac_notify_laundry

  monitorer_volume_slider: !secret monitorer_volume_slider
  monitorer_mute_off: !secret monitorer_mute_off
  monitorer_mute_on: !secret monitorer_mute_on

  fullykiosk_brightness_slider: !secret fullykiosk_brightness_slider
  fullykiosk_load_start_url: !secret fullykiosk_load_start_url
  fullykiosk_restart_app: !secret fullykiosk_restart_app
  fullykiosk_screensaver_on: !secret fullykiosk_screensaver_on
  fullykiosk_screensaver_off: !secret fullykiosk_screensaver_off

  reference_click: !secret reference_click
  reference_kill: !secret reference_kill
  reference_monitors: !secret reference_monitors
  reference_headphones: !secret reference_headphones

  restart_hass_docker: !secret restart_hass_docker
  clear_logs: truncate -s 0 /config/home-assistant.log
  update_data_kwh: !secret update_data_kwh

light:
  - platform: group
    name: Belysning
    entities: ['light.tvlampa', 'light.golvlampa']

  - platform: group
    name: Hall
    entities: ['light.hallampa_1', 'light.hallampa_2', 'light.hallampa_3']

  - platform: group
    name: Badrum
    entities: ['light.vask_vanster', 'light.vask_hoger']

  - platform: group
    name: Taklampor
    entities: ['light.spot_1', 'light.spot_2']

  - platform: group
    name: alla_lampor_utom_hall
    entities:
      ['light.fonsterlampa', 'light.tvlampa', 'light.golvlampa', 'light.datorlampa', 
      'light.vask_hoger', 'light.vask_vanster', 'light.kladkammare_2', 'light.taklampa', 
      'light.mattias', 'light.sanja', 'light.spot_1', 'light.spot_2']

homekit:
  ip_address: !secret homekit_ip_address
  auto_start: false
  filter:
    include_entities:
      ['switch.wemo_flakt', 'switch.wemo_monitorer', 'switch.dator_template', 'media_player.sony_bravia_tv', 
      'media_player.samsung', 'switch.playstation_template', 'input_boolean.motion_hall', 'switch.fan_anslut', 'script.samsung_tv_energy_saving', 
      'input_boolean.motion_garderob', 'input_boolean.motion_badrum', 'script.auto_hemma', 'script.auto_stang_allt']
  entity_config:
    switch.wemo_flakt:
      name: Fläkt
    switch.fan_anslut:
      name: Fläkt 2
    script.samsung_tv_energy_saving:
      name: Eko
    switch.wemo_monitorer:
      name: Monitorer
      type: outlet
    switch.dator_template:
      name: Dator
    media_player.sony_bravia_tv:
      name: Tv
      feature_list:
        - feature: on_off
    media_player.samsung:
      name: Samsung Tv
      feature_list:
        - feature: on_off
    switch.playstation_template:
      name: Playstation
    script.auto_hemma:
      name: Hemma
    script.auto_stang_allt:
      name: Stäng allt

cloud:
  google_actions:
    filter:
      include_entities:
        ['switch.wemo_flakt', 'switch.wemo_monitorer', 'switch.dator_template', 'media_player.sony_bravia_tv', 
        'media_player.samsung', 'switch.playstation_template', 'media_player.playstation_4', 'switch.fan_anslut', 'script.samsung_tv_energy_saving', 
        'switch.fullykiosk_screen', 'switch.fullykiosk_screensaver', 'script.auto_hemma', 'script.auto_stang_allt']
    entity_config:
      switch.wemo_flakt:
        name: Fläkt
        aliases: ['Fläkt', 'Fläkten']
        room: Studio
      switch.fan_anslut:
        name: Fläkt
        aliases: ['Fläkt', 'Fläkten']
        room: Sovrum
      script.samsung_tv_energy_saving:
        name: Eko
        aliases: ['Eko', 'Eko-läge', 'Samsung eko']
        room: Sovrum
      switch.wemo_monitorer:
        name: Monitorer
        room: Studio
      switch.dator_template:
        name: Dator
        aliases: ['Dator', 'Datorn', 'Datan', 'iMac']
        room: Studio
      media_player.sony_bravia_tv:
        name: Tv
        aliases:
          ['Tv', 'Sony Tv', 'Sony Bravia Tv', 'Bravia Tv', 
          'Vardagsrums Tv', 'Vardagsrums Teven', 'Tv Vardagsrum']
        room: Vardagsrum
      media_player.samsung:
        name: Samsung Tv
        aliases: ['Samsung Tv', 'Sovrums Tv', 'Sovrums Teven', 'Tv Sovrum']
        room: Sovrum
      switch.playstation_template:
        name: Playstation
        aliases: ['Playstation', 'PS4', 'Playstation 4']
        room: Vardagsrum
      script.auto_hemma:
        name: Hemma
        aliases: ['Hemma', 'Auto hemma', 'Jag är hemma']
        room: Hall
      script.auto_stang_allt:
        name: Stäng allt
        aliases: ['Stäng allt', 'Auto Stäng allt']
        room: Hall
